#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/../splynx-addon-base-2/vendor/autoload.php');
require(__DIR__ . '/../splynx-addon-base-2/vendor/yiisoft/yii2/Yii.php');

$baseDir = __DIR__;
$configPath = $baseDir . '/config/console.php';

$application = new splynx\base\ConsoleApplication($baseDir, $configPath);
$exitCode = $application->run();
exit($exitCode);
